### ISSUE TITLE
Switching groups with group management changes insignia to that group

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Stratis#1]
**Steps to Reproduce**:
1. Spawn in as any role.
2. Note your rank symbol insignia on the shoulder.
3. Enter group management (*default: U*)
4. Switch to a different group.
5. Note insignia.

**Observed:**
When switching groups with the dynamics groups manager the player's insignia will be changed to the BIS insignia of the group he joins; for example the player may originally start out with the rank of Private but when switching groups it will be changed to the Zeus insignia.

Need to disable this so that the player's rank insignia stays.

**Comment by Diffusion9** [comment]
https://community.bistudio.com/wiki/Dynamic_Groups
Also relevant to #15 

```
if (isServer) then
{
   private ["_group", "_leader", "_data"];
   _group  = group player;
   _leader = leader _group;
   _data   = [nil, "Awesome Group", false]; // [<Insignia>, <Group Name>, <Private>]
 
   ["RegisterGroup", [_group, _leader, _data]] call BIS_fnc_dynamicGroups;
};
```

**Comment by Diffusion9** [comment]
Fixed by forking BIS' Dynamic Groups function and commenting out the insignia replacements. Should be ready for implementation after lane merges in the uniform and regearing.

**Comment by jmlane** [comment]
Just merge your stuff when it is ready. It doesn't need my changes specifically does it?

**Comment by Diffusion9** [comment]
This was pre-arm break so I figured the  changes would be in earlier :dancers:. Merged in now.
