### ISSUE TITLE
Swap uniform to U_IG_Guerrilla_6_1, update rvmat with U_I_CombatUniform

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Stratis#11]
Should get around the uniform blacklisting, while keeping the proper uniform model. Can just reference the AAF Combat Uniform rvmat to get rid of the "knitted sweater" look of the Guerilla Apparel that we were originally using.

**Comment by jmlane** [comment]
:+1: Sounds good.

I noticed in local testing that my dead bodies reverted to vanilla AAF uniform textures. Is that a separate issue or related to this one?

**Comment by Diffusion9** [comment]
Wasn't happening on the live environment last night; probably related to your testing setup.

**Comment by Diffusion9** [comment]
The rvmat for the AAF Combats is "a3\characters_f_beta\indep\data\ia_soldier_01_clothing.rvmat", with the material selection being 0, so:

obj setObjectMaterialGlobal [0, "a3\characters_f_beta\indep\data\ia_soldier_01_clothing.rvmat"];

We'll need to add a uniform handler so that uniforms revert to their proper texture when being taken off and added back again.

**Comment by Diffusion9** [comment]
equipPlayer.sqf
```
_unit forceAddUniform "U_IG_Guerrilla_6_1";
```

setUniform.sqf
```
_unit setObjectTextureGlobal [0,"textures\uniform\uniform.paa"];
_unit setObjectMaterialGlobal [0, "a3\characters_f_beta\indep\data\ia_soldier_01_clothing.rvmat"];
```

**Comment by Diffusion9** [comment]
Done.

**Comment by jmlane** [comment]
:+1: Thanks
