### ISSUE TITLE
Build script for preparing PBO

### ISSUE THREAD

**Issue by jmlane** [Diffusion9/Sandbox.Stratis#12]
I noticed the file size of the mission was pretty significant last night when my client was downloading it. I  suspect that if the PBO is being built using the same directory as the repository, the Git folder containing the repository metadata is being packaged up and send across the network to all joining clients. This is problematic and an easy way to ensure the mission files are striped of any junk that isn't required for deployment would be a simple build script.

**Comment by jmlane** [comment]
ACE and CBA use [a collection of Python scripts](https://github.com/CBATeam/CBA_A3/tree/master/tools) for this and other purposes (validation, calling Mikero's tools, etc), but that might be overkill for what we are doing. I'm not super knowledge about [PowerShell](https://msdn.microsoft.com/en-us/powershell/mt173057.aspx) but that's probably the lowest common denominator since it can be run on modern Windows machines without any extra installs.

**Comment by Diffusion9** [comment]
File size is significant because of the uniform texture. I might've accidentally made a package with the git data last night when we were rushing to get it online before the op.

Building the PBO is pretty inconsequential, and I've already got something integrated into the windows shell that does it automatically.

**Comment by jmlane** [comment]
Whatever works for you since you're deploying it. I generally prefer to automate things I can than rely on my feeble squishy brain to not screw it up at some point like when I'm pressed for time or distracted.
