### ISSUE TITLE
AI Gear

### ISSUE THREAD

**Issue by DEL-J** [Diffusion9/Sandbox.Stratis#14]
[AIGear.zip](https://github.com/Diffusion9/Sandbox.Stratis/files/112822/AIGear.zip)

This file may need to be reformatted and or rewritten to fit neatly into the new sandbox, but the grunt work is done, I'll leave the rest to you brainy guys. I'll be fleshing this file out more whenever we get it implemented into the server. Soon, I will have a file that dictates AI groups that spawn and their behavior upon spawning as well.

**Comment by Diffusion9** [comment]
@DEL-J We'll need everything (AI Gear and whatever groups you want) done before we start on any code or do any implementing to avoid refactoring down the road. Will start work on this whenever we have the full monty.

**Comment by jmlane** [comment]
Based on testing of #22, @DEL-J identified the following outstanding issues:

- [ ] Non-playable BLU_F units should be replaced with police.
- [ ] Some Militia do not get the correct uniform (underwear).
