### ISSUE TITLE
Rank insignias need to be "patchified"

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Stratis#2]
The rank insignia currently look too fake\graphic-y. They need to be turned into actual patches that have a stitched\embroidered look.

**Comment by Diffusion9** [comment]
Half-Cat is working on this and has already showed me some preliminary work. He will show it to DEL-J and eventually we'll integrate them.

**Comment by jmlane** [comment]
:+1: Good stuff!

**Comment by Diffusion9** [comment]
Half-Cat's initial ranks have been integrated
