### ISSUE TITLE
Equipped weapons are not included in the disconnected player body cleanup

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Stratis#3]
**Steps to Reproduce**:
1. Join and select a role
2. Equip a weapon but ensure that no other equipment is in your uniform\vest containers.
3. Disconnect from the server.

**Observed:**
The player's body and weapon are deleted if they disconnect from the server with a weapon equipped. Need to add an additional check that looks for an equipped weapon so the players body will not be deleted if the player has a weapon equipped (but no other items).

The eventHandler for this is in init.sqf under "// Disconnected Player Body Cleanup"

**Comment by jmlane** [comment]
This one is pretty straight forward. Should have it sorted out shortly.
