### ISSUE TITLE
Idea: Use BitCoin

### ISSUE THREAD

**Issue by DEL-J** [Diffusion9/Sandbox.Stratis#30]
The thought just occurred to me that since Athena Security Group is an international private military company and our setting is the early twenty twenties, it may be entertaining and help with world-building if we use BTC as our base currency, rather than USD. BitCoin is used internationally at present and doesn't seem to be slowing down. I could make the changes myself, but wanted to drop the idea and get feedback instead of making assumptions that everyone agrees with me.

**Comment by jmlane** [comment]
I don't really see the appeal and I consider myself to be a pretty big neckbeard. I'm not in opposition however.

If I was actually getting paid for my service, I'd definitely want it in hard currency, preferably a valuable one like USD or Euro.

**Comment by Diffusion9** [comment]
I'm ambivalent. Realistically, I don't really see the USD being removed as the global peg anytime soon. Although, with that being said the start of the Arma 3 single-player campaign seems to indicate that the US and Euro economies are doing poorly which is the cause for the drawdown, so maybe the USD is on the way out.
