### ISSUE TITLE
Child markers within x meters of their parent base should not show

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Stratis#37]
When bases are deployed close to each other, only the parent label should show.

**Steps to Reproduce:**
1. Deploy a Tactical Operations Centre
2. Deploy a Field Command Post nearby

**Observed:**
If players were to construct a makeshift base using the TOC, FCP, and the Patrol Bases the map markers would be very cluttered. In a case like this only the TOC marker should show on the map.

Child base map markers should only appear when deployed > 100 m from their parent base.

**Comment by jmlane** [comment]
This seems like something I can handle unless you're already planning to do it @Diffusion9.

**Comment by Diffusion9** [comment]
'gopher it @jmlane.
Although if you are going to leverage some of the marker data in baseData, be advised that there will be some very minor changes to the baseData arrangement coming when I make the base deployment update ... but, likely just a shift in position of the marker data in the baseData array.

**Comment by jmlane** [comment]
What's the value of "x meters" at which we want to hide things?

**Comment by Diffusion9** [comment]
Probably have to play with it a little bit to see what looks best. I'm guessing maybe 100 - 200 meters might be fair.

**Comment by Diffusion9** [comment]
Merged into #56
