### ISSUE TITLE
Move Reinforcement Point to MOB/TOC Helipad

### ISSUE THREAD

**Issue by DEL-J** [Diffusion9/Sandbox.Stratis#38]
Title sums it up. I think it's an unnecessary step that we have now where it delivers to somewhere that could be completely irrelevant to the all other objects.

**Comment by Diffusion9** [comment]
Thumbs up to this. Delivering to the active MOB/FOB/TOC is a great idea, and definitely easy to do.

**Comment by jmlane** [comment]
:+1: Agreed

**Comment by Diffusion9** [comment]
@jmlane Do you want to take this on?
