### ISSUE TITLE
Prevent duplication of ASG-default gear

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Stratis#4]
*From DEL-J*:
We end up with lots of duplicate vests, helmets, and uniforms because lazy players store them in the official boxes instead of putting away just the stuff that belongs in the boxes.

Is there any way we could delete the uniforms, helmets, and vests when they are placed in the boxes without deleting the items inside of those items' inventories?

**Comment by Diffusion9** [comment]
In a perfect world this is how I'd like this to be engineered:

- Player places an ASG-default uniform into a squad box.
- If the uniform or vest is empty it is deleted to avoid building up a stock of useless default equipment.
- If the uniform or vest has items in it, the items are removed and placed into the squad box and then the uniform or vest is deleted.
- Brain buckets can be immediately deleted since they have no storage anyways.

**Comment by jmlane** [comment]
:+1:

**Comment by Diffusion9** [comment]
On second thoughts, not sure I like this idea.
Even if we do create something that automatically unpacks any vests or uniforms that are put in, if somebody absentmindedly puts their vest in the box before an op begins or something, that means the vest gets deleted and we have somebody that has to relog to get the gear back.. so I think I will close this for now and say that its up to everybody to not be lazy and police the gear boxes correctly.

**Comment by jmlane** [comment]
Good observation. I concur. We could add admin logistical scripts for clean-up if this becomes a problem.

**Comment by Diffusion9** [comment]
agreed
