### ISSUE TITLE
Some uniforms are not being applied after death

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Stratis#40]
As per the op on Thursday (2016-02-18), some people were being reinforced without the uniform texture being applied.

**Comment by jmlane** [comment]
This is most likely a timing issue having to do with how clients process remote object updates, e.g. `setUniform` isn't actually applied on remote clients before `setObjectTextureGlobal` is executed, despite it working on the client owning the object.

**Comment by Diffusion9** [comment]
I would've liked to have been killed with the rest of the platoon so I could've did a census on everybody who was missing their uniforms. Some people had them, some people didn't. I wonder if it was just random people on a certain helo flight, or if one entire flight didn't have the correct texture deployed.

**Comment by jmlane** [comment]
I have no way of knowing what is long enough and what is too long, but 67534d0 generally is how I think this will be fixed. Do we want to do testing or just push it up and observe the results live?

**Comment by Diffusion9** [comment]
As was once said: "DO IT LIVE"

**Comment by jmlane** [comment]
Changes on master, now it needs to be tested.

**Comment by jmlane** [comment]
We only had one (intentional) respawn and his uniform looked correct. His incapacitated body did not however, so I pushed 37ec5e6 to see if that will do it.

**Comment by jmlane** [comment]
@DEL-J said this was no longer a critical focus since it will be a non-issue once the new medical script lands.

**Comment by Diffusion9** [comment]
Sorta fixed with 043b0b6.
Texture flicker on death, but flicker is better than broken texture.
Can implement a more serious solution later, or never (if the medical script gets online).
