### ISSUE TITLE
Respawn helo is not waiting for a full load before delivering

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Stratis#41]
When players are killed, it seems only a handful of players are loaded into the helicopter.

**Comment by jmlane** [comment]
This is working as intended IMO. It's only a problem if a lot of people are respawning at intervals of 10–120 seconds. Any less and they are loaded together, any more and the helo is available again to load them.

Not everyone will have the helo on standby for them personally if lots of people are respawning at regular intervals.

**Comment by Diffusion9** [comment]
Yeah you're right, we probably shouldn't even bother. Although I guess if we can come up with a system down the road that would watch for near-deaths that would work, for now I think we're fine.

**Comment by jmlane** [comment]
Agreed
