### ISSUE TITLE
Players are not being kicked out of the respawn huron on landing.

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Stratis#5]
When the logistics Huron arrives at respawnIsland and it contains more than 4 players, the players are not being kicked out of the helicopter at the correct time.

The helicopter will land, and then take off again without unloading the players. After the helicopter lifts off the players will be removed, whereupon they will fall to their deaths.

**Comment by Diffusion9** [comment]
I think its a problem with the waitUntil block in initServer.sqf (lines 125 to 135). Pretty sure I wrote that section before I knew wtf I was doing with waitUntil blocks.

That whole damn section (right down to 138) is pretty sloppy anyways and could stand to be rewritten in non-idiot.

**Comment by Diffusion9** [comment]
```
waitUntil {
	if (getPOS (heloName select 2) <= 1) then {
		_list = assignedCargo (respawnHelo select 0);
		{_x action ["Eject", vehicle _x]} forEach _list;
		true;
	};
	(getPOS (heloName select 2) <= 1);
};
```

Also, should probably do an explicit check for players in the cargo instead of just relying on a sleep.

`((assignedCargo (respawnHelo select 0)) isEqualTo [])`

**Comment by jmlane** [comment]
I [started cleaning this stuff up a bit](https://github.com/Diffusion9/Sandbox.Stratis/compare/master...jmlane:helo-reinforcements) and added a [check for no remaining assigned cargo](https://github.com/Diffusion9/Sandbox.Stratis/commit/c279648258d68e18ffe8560a4669e52046aa7f46) before takeoff. I didn't have time to test it though.
