### ISSUE TITLE
AI Mortar: Functionality Rewrite

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Stratis#66]
- [x] 5 targets must be detected to begin fire mission (_setTriggerStatements_).
- [x] No friendly targets within 200 m of the target area (_fn_mortarLogic_).
- [x] Mortars abandon their weapons and destroy them if enemies are within 200 m.
- [x] Spawn correct soldier class as mortar men.
- [x] Secondary mortar is manned.
- [x] Secondary mortar participates in FFE.
- [x] Custom setDir switch.
- [x] Unlimited ammo toggle.
- [x] Dynamically kills all triggers and scripts when conditions for cancellation are met.

**Comment by Diffusion9** [comment]
Completed in dev.

**Comment by DEL-J** [comment]
GREAT work, Dave!
