### ISSUE TITLE
Add ETA to Reinforcing message

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Stratis#8]
The reinforcing message needs an ETA timer, and more feedback that the game isn't completely frozen.

**Comment by jmlane** [comment]
:+1: Totally agreed.

**Comment by jmlane** [comment]
Now that I've looked at the code for a bit, I don't really know how we're going to do this given the helicopter can be busy doing whatever for however long.

Any thoughts?

**Comment by Diffusion9** [comment]
I figure we'll have to make a solution combining distance\distance2D with speed or velocity and then just do an on-the-fly calculation.

I also had a thought that instead of having the screen go black we could do some sort of semi-observer thing, but I don't know. We'll see about that one. We still want to maintain the relative level of quasi-realism that is in the spirit of the sandbox.

**Comment by jmlane** [comment]
:+1: for the spectator thing. I was thinking the same thing last night, but had similar reservations and wanted to discuss the concept with you and @DEL-J further.

**Comment by Diffusion9** [comment]
Enhanced, with the implementation of the KIA UAV
