### ISSUE TITLE
Player deaths at the reinforcement drop-off point are not correctly handled.

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Stratis#9]
**Steps to Reproduce**
1. Player death
2. Reinforce on the Huron
3. After landing and being ejected kill yourself

**Observed**:
Deaths at the reinforcement drop-off point are not correctly handled; players will not be added to the reinforcement queue.

**Comment by jmlane** [comment]
I'll see if I can take a look at this tomorrow. I will assign myself to the issue if I start working on it.

**Comment by jmlane** [comment]
Resolved in #13.
